// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXsZFQ_hSkiTvvdzOyN35iwW5heDH1mis',
    appId: '1:3752012208:web:f5e676693576de61ca8e75',
    messagingSenderId: '3752012208',
    projectId: 'foodies2-57e85',
    authDomain: 'foodies2-57e85.firebaseapp.com',
    storageBucket: 'foodies2-57e85.appspot.com',
    measurementId: 'G-9HDG4JK4FZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVPrlTrEdum5sh8VSgTZxxR10xCw9gfbk',
    appId: '1:3752012208:android:d75d9357323c3c50ca8e75',
    messagingSenderId: '3752012208',
    projectId: 'foodies2-57e85',
    storageBucket: 'foodies2-57e85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAWKo4hHusUpOE8_LdgZV5nkS6FvHuHgM',
    appId: '1:3752012208:ios:aeb61bc2f48176e3ca8e75',
    messagingSenderId: '3752012208',
    projectId: 'foodies2-57e85',
    storageBucket: 'foodies2-57e85.appspot.com',
    iosClientId: '3752012208-qc8vmv9eio48igu0hongbqask5gl3a7h.apps.googleusercontent.com',
    iosBundleId: 'com.example.habit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAWKo4hHusUpOE8_LdgZV5nkS6FvHuHgM',
    appId: '1:3752012208:ios:640812ed9f884aaaca8e75',
    messagingSenderId: '3752012208',
    projectId: 'foodies2-57e85',
    storageBucket: 'foodies2-57e85.appspot.com',
    iosClientId: '3752012208-oo5tagq22n19q8j95a0fnm2jrl6tm710.apps.googleusercontent.com',
    iosBundleId: 'com.example.habit.RunnerTests',
  );
}
